import { BotFlow } from './bot-flow';

export const DEFAULT_BOT_FLOWS: BotFlow[] = [
  // 1. CLÍNICA MÉDICA & ODONTOLOGIA
  {
    id: 'flow-clinica-saude',
    name: '🩺 Clínica & Consultório Médico / Odontológico',
    segment: 'Saúde & Estética',
    companyName: 'Clínica Saúde & Sorriso',
    description: 'Triagem de pacientes, consulta de especialidades, convênio vs particular e solicitação de agendamento.',
    isActive: true,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos sua atenção! Caso precise cuidar da sua saúde no futuro, conte conosco.',
    faqRules: [
      {
        id: 'faq-1',
        keywords: ['endereco', 'localizacao', 'onde fica', 'local'],
        reply: 'Estamos localizados na Avenida Principal, nº 500, Sala 302 (com estacionamento próprio conveniado).',
      },
      {
        id: 'faq-2',
        keywords: ['convenio', 'plano', 'unimed', 'bradesco', 'amil', 'sulamerica'],
        reply: 'Atendemos os principais convênios médicos e odontológicos, além de consultas e procedimentos particulares com condições facilitadas.',
      },
      {
        id: 'faq-3',
        keywords: ['preco', 'valor', 'quanto custa', 'tabela'],
        reply: 'Os valores variam de acordo com o procedimento e avaliação clínica. Nossas consultas partem de valores especiais com retorno incluso.',
      }
    ],
    steps: [
      {
        id: 'step-inicio',
        title: 'Boas-vindas e Especialidade',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Seja muito bem-vindo(a) à *{{minha_empresa}}*! 🩺✨\n\nComo podemos te ajudar hoje?\n\n*1️⃣* - Agendar Consulta ou Exame\n*2️⃣* - Tratamentos Odontológicos\n*3️⃣* - Dúvidas sobre Convênios\n*4️⃣* - Falar com a Recepção`,
        options: [
          { id: 'opt-1', key: '1', label: 'Consulta / Exame', nextStepId: 'step-coleta-nome' },
          { id: 'opt-2', key: '2', label: 'Odontologia', nextStepId: 'step-odonto' },
          { id: 'opt-3', key: '3', label: 'Convênios', nextStepId: 'step-convenios' },
          { id: 'opt-4', key: '4', label: 'Recepção Humana', nextStepId: 'step-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-coleta-nome',
        title: 'Identificação do Paciente',
        type: 'question_text',
        message: 'Excelente! Para localizarmos sua ficha e agilizarmos o atendimento, por favor digite seu *Nome Completo*:',
        freeTextNextStepId: 'step-coleta-periodo',
        saveToField: 'nome_paciente',
      },
      {
        id: 'step-coleta-periodo',
        title: 'Preferência de Horário',
        type: 'question_choice',
        message: 'Obrigado! Qual é o melhor período para o seu atendimento?\n\n*1️⃣* - Manhã (08h às 12h)\n*2️⃣* - Tarde (13h às 18h)\n*3️⃣* - Qualquer horário disponível',
        options: [
          { id: 'per-1', key: '1', label: 'Manhã', nextStepId: 'step-finalizacao', action: 'qualify_lead' },
          { id: 'per-2', key: '2', label: 'Tarde', nextStepId: 'step-finalizacao', action: 'qualify_lead' },
          { id: 'per-3', key: '3', label: 'Qualquer', nextStepId: 'step-finalizacao', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-odonto',
        title: 'Tratamento Dentário',
        type: 'question_choice',
        message: 'Trabalhamos com Limpeza, Clareamento, Aparelhos, Implantes e Restaurações.\n\nQual tratamento você procura?\n\n*1️⃣* - Avaliação Geral / Limpeza\n*2️⃣* - Aparelho Ortodôntico ou Alinhadores\n*3️⃣* - Implantes e Próteses\n*4️⃣* - Clareamento Dental',
        options: [
          { id: 'od-1', key: '1', label: 'Limpeza', nextStepId: 'step-coleta-nome' },
          { id: 'od-2', key: '2', label: 'Aparelho', nextStepId: 'step-coleta-nome' },
          { id: 'od-3', key: '3', label: 'Implantes', nextStepId: 'step-coleta-nome' },
          { id: 'od-4', key: '4', label: 'Clareamento', nextStepId: 'step-coleta-nome' },
        ],
      },
      {
        id: 'step-convenios',
        title: 'Convênios Aceitos',
        type: 'question_choice',
        message: 'Aceitamos os principais convênios do mercado! Deseja atendimento por convênio ou particular com desconto à vista?\n\n*1️⃣* - Desejo agendar por Convênio\n*2️⃣* - Desejo agendar Particular',
        options: [
          { id: 'cv-1', key: '1', label: 'Convênio', nextStepId: 'step-coleta-nome' },
          { id: 'cv-2', key: '2', label: 'Particular', nextStepId: 'step-coleta-nome' },
        ],
      },
      {
        id: 'step-finalizacao',
        title: 'Confirmação e Triagem',
        type: 'closing',
        message: 'Perfeito! Seus dados e preferências foram registrados. Nossa equipe de recepção entrará em contato em instantes para confirmar a melhor data e horário para você. Tenha um ótimo dia! 🩺',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-humano',
        title: 'Transferência para Recepção',
        type: 'closing',
        message: 'Com certeza! Já notifiquei nossa recepção. Um atendente humano vai continuar a conversa com você aqui em instantes. Por favor, aguarde só um momento!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 2. PET SHOP & CLÍNICA VETERINÁRIA
  {
    id: 'flow-petshop',
    name: '🐾 Pet Shop & Clínica Veterinária',
    segment: 'Pet Shop & Animais',
    companyName: 'Mundo Pet & Cia',
    description: 'Agendamento de banho e tosa, consultas veterinárias, táxi dog e produtos.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Sem problemas! Caso seu pet precise de cuidados ou carinho, estamos à disposição.',
    faqRules: [
      {
        id: 'faq-pet-1',
        keywords: ['taxi', 'leva e traz', 'transporte', 'buscar'],
        reply: 'Sim! Temos serviço de Táxi Dog seguro com veículo climatizado para buscar e levar seu pet em domicílio.',
      },
      {
        id: 'faq-pet-2',
        keywords: ['endereco', 'onde fica', 'bairro'],
        reply: 'Estamos localizados na Rua dos Animais, nº 120, com fácil estacionamento na porta!',
      }
    ],
    steps: [
      {
        id: 'step-pet-inicio',
        title: 'Boas-vindas Pet',
        type: 'question_choice',
        message: `{Oi|Olá}! Bem-vindo(a) ao *{{minha_empresa}}*! 🐶🐱\n\nComo podemos cuidar do seu melhor amigo hoje?\n\n*1️⃣* - Banho & Tosa\n*2️⃣* - Consulta Veterinária ou Vacinas\n*3️⃣* - Rações, Remédios e Acessórios\n*4️⃣* - Falar com Atendente`,
        options: [
          { id: 'popt-1', key: '1', label: 'Banho & Tosa', nextStepId: 'step-pet-banho' },
          { id: 'popt-2', key: '2', label: 'Veterinário', nextStepId: 'step-pet-vet' },
          { id: 'popt-3', key: '3', label: 'Produtos', nextStepId: 'step-pet-produtos' },
          { id: 'popt-4', key: '4', label: 'Atendente', nextStepId: 'step-pet-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-pet-banho',
        title: 'Porte do Animal',
        type: 'question_choice',
        message: 'Ótimo! Qual é o porte do seu pet?\n\n*1️⃣* - Porte Pequeno (Poodle, Shih Tzu, Yorkshire, etc.)\n*2️⃣* - Porte Médio (Beagle, Cocker, Bulldog, etc.)\n*3️⃣* - Porte Grande (Golden, Labrador, Pastor, etc.)\n*4️⃣* - Gato',
        options: [
          { id: 'porte-1', key: '1', label: 'Pequeno', nextStepId: 'step-pet-taxi' },
          { id: 'porte-2', key: '2', label: 'Médio', nextStepId: 'step-pet-taxi' },
          { id: 'porte-3', key: '3', label: 'Grande', nextStepId: 'step-pet-taxi' },
          { id: 'porte-4', key: '4', label: 'Gato', nextStepId: 'step-pet-taxi' },
        ],
      },
      {
        id: 'step-pet-taxi',
        title: 'Opção de Transporte',
        type: 'question_choice',
        message: 'Você prefere trazer o pet ou utilizar nosso serviço de *Táxi Dog (Leva e Traz)*?\n\n*1️⃣* - Eu mesmo levo na loja\n*2️⃣* - Quero o serviço de Táxi Dog',
        options: [
          { id: 'tx-1', key: '1', label: 'Vou levar', nextStepId: 'step-pet-final', action: 'qualify_lead' },
          { id: 'tx-2', key: '2', label: 'Táxi Dog', nextStepId: 'step-pet-final', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-pet-vet',
        title: 'Serviço Veterinário',
        type: 'question_choice',
        message: 'Nossa equipe veterinária está de prontidão! Qual a necessidade do seu pet?\n\n*1️⃣* - Vacinação de Rotina (V10, Antirrábica, etc.)\n*2️⃣* - Consulta Clínica Geral\n*3️⃣* - Emergência',
        options: [
          { id: 'vet-1', key: '1', label: 'Vacina', nextStepId: 'step-pet-final', action: 'qualify_lead' },
          { id: 'vet-2', key: '2', label: 'Consulta', nextStepId: 'step-pet-final', action: 'qualify_lead' },
          { id: 'vet-3', key: '3', label: 'Emergência', nextStepId: 'step-pet-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-pet-produtos',
        title: 'Catálogo de Produtos',
        type: 'closing',
        message: 'Temos grande variedade de rações Super Premium, medicamentos, antipulgas e petiscos! Digite abaixo o que você precisa que nossa equipe de vendas já te passa os preços e disponibilidade de pronta entrega.',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-pet-final',
        title: 'Encerramento Pet',
        type: 'closing',
        message: 'Perfeito! Anotei a solicitação. Nossa equipe de agendamento já vai te chamar aqui para confirmar o melhor horário na agenda do pet! 🐾',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-pet-humano',
        title: 'Atendente Humano',
        type: 'closing',
        message: 'Já avisei nossa equipe na loja. Um atendente vai continuar sua conversa agora mesmo!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 3. TECNOLOGIA, SITES & PROGRAMAS
  {
    id: 'flow-tecnologia-software',
    name: '💻 Empresa de TI, Sites & Sistemas',
    segment: 'Tecnologia & Software',
    companyName: 'TechSolutions Digital',
    description: 'Diagnóstico de projeto digital, criação de sites, lojas virtuais, sistemas sob medida e automação comercial.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o retorno! Salve nosso contato para quando sua empresa precisar de tecnologia e automação.',
    faqRules: [
      {
        id: 'faq-tech-1',
        keywords: ['portfolio', 'sites feitos', 'exemplos', 'trabalhos'],
        reply: 'Você pode conferir nossos cases de sucesso e projetos recentes com sites rápidos, seguros e integrados ao WhatsApp em nosso portfólio oficial.',
      },
      {
        id: 'faq-tech-2',
        keywords: ['prazo', 'tempo', 'demora', 'dias'],
        reply: 'Landing pages e sites institucionais são entregues em média entre 5 a 10 dias úteis. Sistemas personalizados seguem cronograma por sprints.',
      }
    ],
    steps: [
      {
        id: 'step-tech-inicio',
        title: 'Apresentação Comercial',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Aqui é da equipe da *{{minha_empresa}}*! 🚀\n\nDesenvolvemos tecnologia e automação para alavancar empresas. Qual solução você gostaria de conhecer?\n\n*1️⃣* - Criação de Site ou Loja Virtual\n*2️⃣* - Sistema de Gestão / App Sob Medida\n*3️⃣* - Robôs e Automação de WhatsApp\n*4️⃣* - Falar com Consultor Técnico`,
        options: [
          { id: 'topt-1', key: '1', label: 'Sites e Lojas', nextStepId: 'step-tech-site' },
          { id: 'topt-2', key: '2', label: 'Sistemas e Apps', nextStepId: 'step-tech-sistema' },
          { id: 'topt-3', key: '3', label: 'Automação WhatsApp', nextStepId: 'step-tech-automacao' },
          { id: 'topt-4', key: '4', label: 'Consultor', nextStepId: 'step-tech-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-tech-site',
        title: 'Tipo de Site',
        type: 'question_choice',
        message: 'Excelente escolha! Um site profissional é o cartão de visitas moderno de qualquer negócio.\n\nQual o objetivo principal do seu novo site?\n\n*1️⃣* - Site Institucional para passar credibilidade e atrair clientes\n*2️⃣* - Landing Page de Alta Conversão para campanhas no Google/Instagram\n*3️⃣* - Loja Virtual (E-commerce) com pagamentos e catálogo',
        options: [
          { id: 'st-1', key: '1', label: 'Institucional', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
          { id: 'st-2', key: '2', label: 'Landing Page', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
          { id: 'st-3', key: '3', label: 'E-commerce', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-tech-sistema',
        title: 'Necessidade do Sistema',
        type: 'question_choice',
        message: 'Desenvolvemos programas em nuvem com controle de clientes, vendas, financeiro e estoque.\n\nQual a prioridade da sua empresa hoje?\n\n*1️⃣* - Informatizar processos manuais / planilhas\n*2️⃣* - Integrar filiais ou equipe externa\n*3️⃣* - Criar aplicativo móvel exclusivo',
        options: [
          { id: 'sis-1', key: '1', label: 'Substituir Planilhas', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
          { id: 'sis-2', key: '2', label: 'Gestão Completa', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
          { id: 'sis-3', key: '3', label: 'App Exclusivo', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-tech-automacao',
        title: 'Automação de WhatsApp',
        type: 'question_choice',
        message: 'Nossos robôs de WhatsApp atendem 24h, qualificam contatos e nunca deixam um cliente sem resposta.\n\nQuantas mensagens ou clientes sua empresa atende em média por dia?\n\n*1️⃣* - Até 20 atendimentos/dia\n*2️⃣* - De 20 a 100 atendimentos/dia\n*3️⃣* - Mais de 100 atendimentos/dia (Alto volume)',
        options: [
          { id: 'aut-1', key: '1', label: 'Até 20', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
          { id: 'aut-2', key: '2', label: '20 a 100', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
          { id: 'aut-3', key: '3', label: 'Mais de 100', nextStepId: 'step-tech-coleta-nome', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-tech-coleta-nome',
        title: 'Nome e Empresa',
        type: 'question_text',
        message: 'Perfeito! Para que nosso consultor prepare uma prévia personalizada sem compromisso, qual é o seu *Nome e o Nome da sua Empresa*?',
        freeTextNextStepId: 'step-tech-final',
        saveToField: 'dados_projeto',
      },
      {
        id: 'step-tech-final',
        title: 'Conclusão Consultoria',
        type: 'closing',
        message: 'Dados anotados com sucesso! Nosso especialista em projetos digitais já está assumindo esta conversa para tirar suas dúvidas e te enviar uma proposta personalizada. Aguarde só um instante! 💻✨',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-tech-humano',
        title: 'Consultor Técnico',
        type: 'closing',
        message: 'Perfeito! Transferi seu atendimento para um de nossos especialistas seniores. Em poucos instantes você será atendido(a).',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 4. IMOBILIÁRIA & CORRETORES
  {
    id: 'flow-imobiliaria',
    name: '🏢 Imobiliária & Corretores de Imóveis',
    segment: 'Imóveis & Construção',
    companyName: 'Prime Imóveis',
    description: 'Captação de compradores e inquilinos, filtro de bairro, perfil de imóvel e agendamento de visitas.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o contato! Quando for o momento certo de encontrar seu novo imóvel, estaremos aqui.',
    faqRules: [
      {
        id: 'faq-imob-1',
        keywords: ['financiamento', 'fgts', 'parcelamento', 'banco'],
        reply: 'Apoiamos em toda a assessoria de financiamento habitacional (Caixa, Itaú, Bradesco, Santander), com simulação gratuita e uso do FGTS!',
      }
    ],
    steps: [
      {
        id: 'step-imob-inicio',
        title: 'Interesse Imobiliário',
        type: 'question_choice',
        message: `{Olá|Oi|Como vai?} Seja bem-vindo(a) à *{{minha_empresa}}*! 🏡🔑\n\nComo podemos te ajudar na sua conquista hoje?\n\n*1️⃣* - Quero Comprar um Imóvel\n*2️⃣* - Quero Alugar um Imóvel\n*3️⃣* - Quero Anunciar / Vender meu Imóvel\n*4️⃣* - Falar com um Corretor`,
        options: [
          { id: 'im-1', key: '1', label: 'Comprar', nextStepId: 'step-imob-tipo' },
          { id: 'im-2', key: '2', label: 'Alugar', nextStepId: 'step-imob-tipo' },
          { id: 'im-3', key: '3', label: 'Anunciar', nextStepId: 'step-imob-proprietario' },
          { id: 'im-4', key: '4', label: 'Corretor', nextStepId: 'step-imob-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-imob-tipo',
        title: 'Tipo de Imóvel',
        type: 'question_choice',
        message: 'Qual tipo de imóvel você está procurando?\n\n*1️⃣* - Apartamento\n*2️⃣* - Casa / Condomínio Fechado\n*3️⃣* - Sala Comercial ou Galpão\n*4️⃣* - Terreno / Lote',
        options: [
          { id: 'tp-1', key: '1', label: 'Apartamento', nextStepId: 'step-imob-bairro', action: 'qualify_lead' },
          { id: 'tp-2', key: '2', label: 'Casa', nextStepId: 'step-imob-bairro', action: 'qualify_lead' },
          { id: 'tp-3', key: '3', label: 'Comercial', nextStepId: 'step-imob-bairro', action: 'qualify_lead' },
          { id: 'tp-4', key: '4', label: 'Terreno', nextStepId: 'step-imob-bairro', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-imob-bairro',
        title: 'Região ou Bairro Desejado',
        type: 'question_text',
        message: 'Excelente! Qual *bairro, região da cidade ou faixa de valor aproximada* você tem em mente?',
        freeTextNextStepId: 'step-imob-final',
        saveToField: 'preferencia_imovel',
      },
      {
        id: 'step-imob-proprietario',
        title: 'Proprietário',
        type: 'question_text',
        message: 'Temos grande demanda de compradores qualificados! Por favor, informe o *endereço do imóvel e se é para venda ou locação*:',
        freeTextNextStepId: 'step-imob-final',
        saveToField: 'dados_imovel_anuncio',
      },
      {
        id: 'step-imob-final',
        title: 'Encaminhamento Corretor',
        type: 'closing',
        message: 'Recebemos suas preferências! Nosso corretor especialista dessa região já está separando as melhores opções no catálogo e vai te enviar fotos e detalhes agora mesmo. Aguarde só um momento! 🔑',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-imob-humano',
        title: 'Atendente Imobiliária',
        type: 'closing',
        message: 'Nosso plantão de atendimento imobiliário já foi notificado. Em instantes um corretor falará com você.',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 5. RESTAURANTE, PIZZARIA & DELIVERY
  {
    id: 'flow-restaurante-delivery',
    name: '🍕 Restaurante, Pizzaria & Delivery',
    segment: 'Alimentação & Delivery',
    companyName: 'Sabor & Família Gastronomia',
    description: 'Envio de cardápio digital, recebimento de pedidos, reservas de mesa e taxa de entrega.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos a atenção! Quando bater aquela fome, estaremos prontos para te atender.',
    faqRules: [
      {
        id: 'faq-rest-1',
        keywords: ['horario', 'abre', 'fecha', 'funcionamento'],
        reply: 'Funcionamos de Terça a Domingo, das 18h às 23h30 para delivery e salão!',
      },
      {
        id: 'faq-rest-2',
        keywords: ['pagamento', 'cartao', 'pix', 'dinheiro', 'vr', 'vale refeicao'],
        reply: 'Aceitamos PIX, cartões de crédito/débito e as principais bandeiras de Vale Refeição (VR, Sodexo, Alelo, Ticket).',
      }
    ],
    steps: [
      {
        id: 'step-rest-inicio',
        title: 'Menu do Restaurante',
        type: 'question_choice',
        message: `{Olá|Oi}! Que alegria ter você aqui no *{{minha_empresa}}*! 🍕🍔\n\nComo podemos te deliciar hoje?\n\n*1️⃣* - Ver Cardápio & Fazer Pedido\n*2️⃣* - Reservar uma Mesa\n*3️⃣* - Status do meu Pedido em Andamento\n*4️⃣* - Falar com o Atendente`,
        options: [
          { id: 'ro-1', key: '1', label: 'Cardápio', nextStepId: 'step-rest-cardapio' },
          { id: 'ro-2', key: '2', label: 'Reserva', nextStepId: 'step-rest-reserva' },
          { id: 'ro-3', key: '3', label: 'Status Pedido', nextStepId: 'step-rest-humano', action: 'transfer_human' },
          { id: 'ro-4', key: '4', label: 'Atendente', nextStepId: 'step-rest-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-rest-cardapio',
        title: 'Envio do Cardápio',
        type: 'question_text',
        message: 'Confira nossas delícias e promoções especiais da semana!\n\nVocê prefere receber pelo nosso *Delivery em casa* ou retirar no balcão? Digite seu pedido ou bairro:',
        freeTextNextStepId: 'step-rest-final',
        saveToField: 'pedido_cliente',
      },
      {
        id: 'step-rest-reserva',
        title: 'Reserva de Mesa',
        type: 'question_text',
        message: 'Adoramos receber celebrações! Para quantas pessoas seria a reserva e para qual dia/horário?',
        freeTextNextStepId: 'step-rest-final',
        saveToField: 'reserva_mesa',
      },
      {
        id: 'step-rest-final',
        title: 'Confirmação do Restaurante',
        type: 'closing',
        message: 'Pedido/solicitação recebida! Nossa equipe do balcão já está processando sua mensagem e vai te confirmar tudo em instantes. Bom apetite! 🍽️',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-rest-humano',
        title: 'Atendente Restaurante',
        type: 'closing',
        message: 'Um de nossos atendentes do caixa/salão já vai falar com você aqui!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 6. ADVOCACIA & JURÍDICO
  {
    id: 'flow-advocacia-juridico',
    name: '⚖️ Escritório de Advocacia & Assessoria Jurídica',
    segment: 'Advocacia & Jurídico',
    companyName: 'Oliveira & Associados Advocacia',
    description: 'Triagem jurídica sigilosa, identificação de área (Trabalhista, Previdenciário / INSS, Família, Cível) e agendamento com advogado.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o contato. Nosso escritório permanece à disposição para quando necessitar de assessoria jurídica.',
    faqRules: [
      {
        id: 'faq-adv-1',
        keywords: ['sigilo', 'confidencial', 'segredo', 'privacidade'],
        reply: 'Todas as informações compartilhadas são estritamente sigilosas, protegidas pelo sigilo profissional da OAB e pela LGPD.',
      },
      {
        id: 'faq-adv-2',
        keywords: ['online', 'presencial', 'distancia', 'video'],
        reply: 'Realizamos atendimentos presenciais em nosso escritório e também teleconsultas por videoconferência para sua comodidade.',
      }
    ],
    steps: [
      {
        id: 'step-adv-inicio',
        title: 'Área do Direito',
        type: 'question_choice',
        message: `{Olá|Oi|Como vai?} Seja muito bem-vindo(a) ao escritório *{{minha_empresa}}*! ⚖️\n\nPara direcionarmos você ao advogado especialista correto, qual é a área do seu interesse?\n\n*1️⃣* - Direitos Trabalhistas (Demissão, Verbas, Rescisão)\n*2️⃣* - Previdenciário / INSS (Aposentadoria, Auxílios, BPC/LOAS)\n*3️⃣* - Direito de Família (Divórcio, Pensão, Inventário, Guarda)\n*4️⃣* - Cível / Consumidor (Contratos, Indenizações, Dívidas)\n*5️⃣* - Falar com o Plantão Jurídico`,
        options: [
          { id: 'adv-1', key: '1', label: 'Trabalhista', nextStepId: 'step-adv-coleta', action: 'qualify_lead' },
          { id: 'adv-2', key: '2', label: 'INSS / Previdenciário', nextStepId: 'step-adv-coleta', action: 'qualify_lead' },
          { id: 'adv-3', key: '3', label: 'Direito de Família', nextStepId: 'step-adv-coleta', action: 'qualify_lead' },
          { id: 'adv-4', key: '4', label: 'Cível / Consumidor', nextStepId: 'step-adv-coleta', action: 'qualify_lead' },
          { id: 'adv-5', key: '5', label: 'Plantão Jurídico', nextStepId: 'step-adv-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-adv-coleta',
        title: 'Breve Relato do Caso',
        type: 'question_text',
        message: 'Entendido. Para que o advogado analise seus direitos antes de entrar em contato, digite seu *Nome Completo* e descreva brevemente a situação:',
        freeTextNextStepId: 'step-adv-processo',
        saveToField: 'relato_caso',
      },
      {
        id: 'step-adv-processo',
        title: 'Processo em Andamento',
        type: 'question_choice',
        message: 'Você já possui algum processo judicial aberto sobre esse assunto com outro advogado?\n\n*1️⃣* - Não possuo processo (Caso novo)\n*2️⃣* - Sim, já possuo processo em andamento',
        options: [
          { id: 'proc-1', key: '1', label: 'Não possuo (Novo)', nextStepId: 'step-adv-final', action: 'qualify_lead' },
          { id: 'proc-2', key: '2', label: 'Já possuo processo', nextStepId: 'step-adv-final', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-adv-final',
        title: 'Conclusão da Triagem',
        type: 'closing',
        message: 'Relato recebido com sigilo absoluto! O advogado responsável pela sua área entrará em contato aqui pelo WhatsApp para esclarecer suas dúvidas e orientar os próximos passos. Aguarde só um instante! ⚖️',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-adv-humano',
        title: 'Plantão Jurídico',
        type: 'closing',
        message: 'Notifiquei nosso plantão de atendimento. Em instantes um advogado falará com você aqui nesta conversa.',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 7. CONTABILIDADE & BPO FINANCEIRO
  {
    id: 'flow-contabilidade-fiscal',
    name: '📊 Contabilidade, Fiscal & Abertura de Empresas',
    segment: 'Contabilidade & Finanças',
    companyName: 'Exata Contabilidade & BPO',
    description: 'Abertura de empresas, migração de contador, desenquadramento de MEI para ME, folha de pagamento e gestão fiscal.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o retorno! Salve nosso contato para quando sua empresa precisar de assessoria contábil e tributária.',
    faqRules: [
      {
        id: 'faq-cnt-1',
        keywords: ['abrir cnpj', 'abertura', 'custo cnpj', 'taxas'],
        reply: 'Cuidamos de todo o processo de abertura do seu CNPJ sem burocracia, orientando o melhor enquadramento tributário para você pagar o menor imposto legal.',
      }
    ],
    steps: [
      {
        id: 'step-cnt-inicio',
        title: 'Serviço Contábil',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Aqui é da *{{minha_empresa}}*! 📊💼\n\nAjudamos empresas a economizarem impostos e organizarem suas finanças. Como podemos te auxiliar?\n\n*1️⃣* - Abrir um novo CNPJ (Empresa do Zero)\n*2️⃣* - Trocar de Contador / Reduzir Impostos\n*3️⃣* - Desenquadrar MEI para ME / Regularizar\n*4️⃣* - BPO Financeiro & Folha de Pagamento\n*5️⃣* - Falar com Contador Responsável`,
        options: [
          { id: 'cnt-1', key: '1', label: 'Abrir CNPJ', nextStepId: 'step-cnt-atividade' },
          { id: 'cnt-2', key: '2', label: 'Trocar Contador', nextStepId: 'step-cnt-faturamento' },
          { id: 'cnt-3', key: '3', label: 'MEI para ME', nextStepId: 'step-cnt-dados' },
          { id: 'cnt-4', key: '4', label: 'BPO Financeiro', nextStepId: 'step-cnt-dados' },
          { id: 'cnt-5', key: '5', label: 'Contador', nextStepId: 'step-cnt-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-cnt-atividade',
        title: 'Atividade do Negócio',
        type: 'question_choice',
        message: 'Excelente! Qual será o ramo principal da sua empresa?\n\n*1️⃣* - Prestação de Serviços (TI, Médicos, Consultorias, etc.)\n*2️⃣* - Comércio / Varejo (Loja, Restaurante, Mercadinho)\n*3️⃣* - E-commerce / Infoproduto / Afiliados\n*4️⃣* - Indústria / Construção Civil',
        options: [
          { id: 'at-1', key: '1', label: 'Serviços', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
          { id: 'at-2', key: '2', label: 'Comércio', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
          { id: 'at-3', key: '3', label: 'E-commerce', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
          { id: 'at-4', key: '4', label: 'Indústria / Construção', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-cnt-faturamento',
        title: 'Faturamento Médio',
        type: 'question_choice',
        message: 'Para simularmos sua economia tributária, qual é a média de faturamento mensal da sua empresa?\n\n*1️⃣* - Até R$ 20 mil / mês\n*2️⃣* - De R$ 20 mil a R$ 100 mil / mês\n*3️⃣* - Acima de R$ 100 mil / mês',
        options: [
          { id: 'fat-1', key: '1', label: 'Até 20k', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
          { id: 'fat-2', key: '2', label: '20k a 100k', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
          { id: 'fat-3', key: '3', label: 'Mais de 100k', nextStepId: 'step-cnt-dados', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-cnt-dados',
        title: 'Identificação da Empresa',
        type: 'question_text',
        message: 'Perfeito! Para gerarmos seu diagnóstico contábil gratuito, qual é o seu *Nome e o Nome da sua Empresa*?',
        freeTextNextStepId: 'step-cnt-final',
        saveToField: 'dados_empresa',
      },
      {
        id: 'step-cnt-final',
        title: 'Finalização Contábil',
        type: 'closing',
        message: 'Informações registradas com sucesso! Nosso contador tributarista entrará em contato em instantes com a análise ideal para o seu negócio. Aguarde só um instante! 📈',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-cnt-humano',
        title: 'Contador de Plantão',
        type: 'closing',
        message: 'Um de nossos especialistas fiscais e contábeis já vai assumir esta conversa!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 8. OFICINA MECÂNICA & SERVIÇOS AUTOMOTIVOS
  {
    id: 'flow-oficina-mecanica',
    name: '🚗 Oficina Mecânica & Auto Center',
    segment: 'Serviços Automotivos',
    companyName: 'AutoCenter Confiança',
    description: 'Agendamento de revisão, freios, suspensão, troca de óleo, ar-condicionado e socorro mecânico.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos a atenção! Salve nosso contato para qualquer emergência ou manutenção do seu carro.',
    faqRules: [
      {
        id: 'faq-aut-1',
        keywords: ['guincho', 'socorro', 'parou', 'pane'],
        reply: 'Temos parceria com serviço de guincho rápido na cidade para resgatar seu veículo e trazê-lo diretamente para a oficina.',
      }
    ],
    steps: [
      {
        id: 'step-aut-inicio',
        title: 'Serviço Automotivo',
        type: 'question_choice',
        message: `{Olá|Oi}! Bem-vindo(a) à *{{minha_empresa}}*! 🚗🔧\n\nCuidamos do seu carro com peças originais e garantia. Qual serviço você precisa?\n\n*1️⃣* - Revisão Preventiva / Troca de Óleo e Filtros\n*2️⃣* - Freios, Suspensão ou Pneus\n*3️⃣* - Diagnóstico de Injeção / Barulhos no Motor\n*4️⃣* - Ar-Condicionado Automotivo\n*5️⃣* - Socorro Mecânico / Guincho\n*6️⃣* - Falar com Mecânico Chefe`,
        options: [
          { id: 'ao-1', key: '1', label: 'Revisão / Óleo', nextStepId: 'step-aut-carro' },
          { id: 'ao-2', key: '2', label: 'Freios / Suspensão', nextStepId: 'step-aut-carro' },
          { id: 'ao-3', key: '3', label: 'Injeção / Barulhos', nextStepId: 'step-aut-carro' },
          { id: 'ao-4', key: '4', label: 'Ar-Condicionado', nextStepId: 'step-aut-carro' },
          { id: 'ao-5', key: '5', label: 'Guincho', nextStepId: 'step-aut-humano', action: 'transfer_human' },
          { id: 'ao-6', key: '6', label: 'Mecânico Chefe', nextStepId: 'step-aut-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-aut-carro',
        title: 'Modelo do Carro',
        type: 'question_text',
        message: 'Para checarmos as especificações técnicas, qual é o *Modelo, Marca e Ano do seu Veículo*?',
        freeTextNextStepId: 'step-aut-dia',
        saveToField: 'dados_veiculo',
      },
      {
        id: 'step-aut-dia',
        title: 'Previsão de Chegada',
        type: 'question_choice',
        message: 'Qual é o melhor momento para trazer o carro na oficina?\n\n*1️⃣* - Hoje mesmo\n*2️⃣* - Amanhã de manhã (08h às 11h)\n*3️⃣* - No decorrer desta semana',
        options: [
          { id: 'd-1', key: '1', label: 'Hoje', nextStepId: 'step-aut-final', action: 'qualify_lead' },
          { id: 'd-2', key: '2', label: 'Amanhã', nextStepId: 'step-aut-final', action: 'qualify_lead' },
          { id: 'd-3', key: '3', label: 'Esta Semana', nextStepId: 'step-aut-final', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-aut-final',
        title: 'Agendamento Confirmado',
        type: 'closing',
        message: 'Informações anotadas! Nosso consultor técnico já reservou um box na oficina e entrará em contato para confirmar sua chegada. Até breve! 🚗💨',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-aut-humano',
        title: 'Plantão Oficina',
        type: 'closing',
        message: 'Já acionei nosso mecânico de plantão. Aguarde só um instante que ele vai te atender agora.',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 9. BELEZA, ESTÉTICA & BARBEARIA
  {
    id: 'flow-estetica-beleza',
    name: '💅 Salão de Beleza, Estética & Barbearia',
    segment: 'Beleza & Estética',
    companyName: 'Studio Bella & Barber',
    description: 'Agendamento de cabelo, manicure, sobrancelhas, limpeza de pele, procedimentos estéticos e barba.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o contato! Quando quiser renovar o visual e cuidar de você, estamos à disposição.',
    faqRules: [
      {
        id: 'faq-est-1',
        keywords: ['endereco', 'onde fica', 'local'],
        reply: 'Estamos no Centro Comercial da cidade, com ambiente climatizado e café especial de boas-vindas!',
      }
    ],
    steps: [
      {
        id: 'step-est-inicio',
        title: 'Procedimento Desejado',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Seja muito bem-vindo(a) ao *{{minha_empresa}}*! ✨💇‍♀️💈\n\nQual cuidado especial você gostaria de agendar hoje?\n\n*1️⃣* - Cabelo (Corte, Mechas, Escova ou Coloração)\n*2️⃣* - Barba & Corte Masculino\n*3️⃣* - Unhas & Manicure/Pedicure\n*4️⃣* - Estética Facial (Sobrancelhas, Limpeza de Pele)\n*5️⃣* - Falar com a Recepção`,
        options: [
          { id: 'eo-1', key: '1', label: 'Cabelo', nextStepId: 'step-est-dia' },
          { id: 'eo-2', key: '2', label: 'Barba / Corte', nextStepId: 'step-est-dia' },
          { id: 'eo-3', key: '3', label: 'Unhas', nextStepId: 'step-est-dia' },
          { id: 'eo-4', key: '4', label: 'Estética Facial', nextStepId: 'step-est-dia' },
          { id: 'eo-5', key: '5', label: 'Recepção', nextStepId: 'step-est-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-est-dia',
        title: 'Dia Preferido',
        type: 'question_choice',
        message: 'Qual período fica mais confortável para o seu momento de beleza?\n\n*1️⃣* - Quinta-feira\n*2️⃣* - Sexta-feira\n*3️⃣* - Sábado\n*4️⃣* - Outro dia da semana',
        options: [
          { id: 'dia-1', key: '1', label: 'Quinta', nextStepId: 'step-est-nome', action: 'qualify_lead' },
          { id: 'dia-2', key: '2', label: 'Sexta', nextStepId: 'step-est-nome', action: 'qualify_lead' },
          { id: 'dia-3', key: '3', label: 'Sábado', nextStepId: 'step-est-nome', action: 'qualify_lead' },
          { id: 'dia-4', key: '4', label: 'Outro dia', nextStepId: 'step-est-nome', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-est-nome',
        title: 'Nome para Reserva',
        type: 'question_text',
        message: 'Perfeito! Por favor, digite seu *Nome* para separarmos o melhor horário na agenda:',
        freeTextNextStepId: 'step-est-final',
        saveToField: 'nome_cliente_reserva',
      },
      {
        id: 'step-est-final',
        title: 'Reserva na Agenda',
        type: 'closing',
        message: 'Excelente! Nossa recepcionista já está finalizando sua reserva e vai te confirmar o horário exato aqui em instantes. Vai ser um prazer te receber! 💖',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-est-humano',
        title: 'Recepção do Salão',
        type: 'closing',
        message: 'Nossa recepção já foi avisada. Em poucos minutos alguém da equipe falará com você.',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 10. MODA, ROUPAS & CALÇADOS (VAREJO)
  {
    id: 'flow-moda-varejo',
    name: '🛍️ Loja de Roupas, Calçados & Moda',
    segment: 'Moda & Varejo',
    companyName: 'Loja Estilo & Conforto',
    description: 'Catálogo de nova coleção, verificação de tamanhos (P ao GG), frete por motoboy e formas de pagamento.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Muito obrigado pela resposta! Acompanhe nossas novidades para conferir lançamentos futuros.',
    faqRules: [
      {
        id: 'faq-mod-1',
        keywords: ['entrega', 'motoboy', 'frete', 'envio'],
        reply: 'Enviamos via motoboy express com entrega no mesmo dia para toda a região metropolitana, além de Correios para todo o Brasil!',
      }
    ],
    steps: [
      {
        id: 'step-mod-inicio',
        title: 'Interesse na Loja',
        type: 'question_choice',
        message: `{Olá|Oi}! Que bom ter você aqui na *{{minha_empresa}}*! 👗👠👜\n\nNossa nova coleção acabou de chegar! Como podemos te ajudar?\n\n*1️⃣* - Ver Fotos e Catálogo da Coleção\n*2️⃣* - Consultar Disponibilidade de Tamanho / Cor\n*3️⃣* - Opções de Entrega e Frete\n*4️⃣* - Falar com uma Vendedora`,
        options: [
          { id: 'mo-1', key: '1', label: 'Catálogo', nextStepId: 'step-mod-interesse' },
          { id: 'mo-2', key: '2', label: 'Tamanho / Cor', nextStepId: 'step-mod-tamanho' },
          { id: 'mo-3', key: '3', label: 'Entrega', nextStepId: 'step-mod-entrega' },
          { id: 'mo-4', key: '4', label: 'Vendedora', nextStepId: 'step-mod-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-mod-interesse',
        title: 'Peça Desejada',
        type: 'question_text',
        message: 'Temos opções incríveis em Vestidos, Conjuntos, Jeans, Calçados e Acessórios! Qual estilo de peça você está buscando hoje?',
        freeTextNextStepId: 'step-mod-final',
        saveToField: 'estilo_procurado',
      },
      {
        id: 'step-mod-tamanho',
        title: 'Tamanho Desejado',
        type: 'question_text',
        message: 'Trabalhamos do P ao Plus Size! Qual é a sua numeração habitual e qual modelo chamou sua atenção?',
        freeTextNextStepId: 'step-mod-final',
        saveToField: 'tamanho_procurado',
      },
      {
        id: 'step-mod-entrega',
        title: 'Bairro de Entrega',
        type: 'question_text',
        message: 'Entregamos via motoboy no mesmo dia! Para qual bairro ou cidade seria a entrega?',
        freeTextNextStepId: 'step-mod-final',
        saveToField: 'bairro_entrega',
      },
      {
        id: 'step-mod-final',
        title: 'Vendedora Separando Fotos',
        type: 'closing',
        message: 'Perfeito! Nossa vendedora já está separando as fotos das peças no seu tamanho e vai te mandar todas as opções com valores e desconto especial à vista. Só um segundo! 🛍️✨',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-mod-humano',
        title: 'Vendedora ao Vivo',
        type: 'closing',
        message: 'Uma de nossas vendedoras já está assumindo seu atendimento para te enviar fotos e tirar dúvidas!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 11. ACADEMIA & FITNESS
  {
    id: 'flow-academia-fitness',
    name: '🏋️‍♂️ Academia, Crossfit & Studio Fitness',
    segment: 'Fitness & Esportes',
    companyName: 'FitLife Academia',
    description: 'Agendamento de aula experimental gratuita, planos mensais/anuais, modalidades e horário de funcionamento.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos a atenção! Quando estiver pronto para focar na sua saúde e disposição, estaremos de portas abertas.',
    faqRules: [
      {
        id: 'faq-fit-1',
        keywords: ['horario', 'abre', 'fecha', 'domingo'],
        reply: 'Funcionamos de Segunda a Sexta das 06h às 23h, e aos Sábados, Domingos e Feriados das 08h às 14h!',
      }
    ],
    steps: [
      {
        id: 'step-fit-inicio',
        title: 'Interesse Fitness',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Bem-vindo(a) à *{{minha_empresa}}*! 🏋️‍♂️💪🔥\n\nPronto(a) para transformar sua saúde e energia? Como podemos te ajudar?\n\n*1️⃣* - Agendar Aula Experimental Gratuita (Passe Livre)\n*2️⃣* - Conhecer Planos e Promoções do Mês\n*3️⃣* - Modalidades (Lutas, Dança, Natação, Pilates)\n*4️⃣* - Falar com a Recepção`,
        options: [
          { id: 'fo-1', key: '1', label: 'Aula Grátis', nextStepId: 'step-fit-objetivo' },
          { id: 'fo-2', key: '2', label: 'Planos', nextStepId: 'step-fit-objetivo' },
          { id: 'fo-3', key: '3', label: 'Modalidades', nextStepId: 'step-fit-objetivo' },
          { id: 'fo-4', key: '4', label: 'Recepção', nextStepId: 'step-fit-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-fit-objetivo',
        title: 'Objetivo de Treino',
        type: 'question_choice',
        message: 'Qual é o seu objetivo principal hoje?\n\n*1️⃣* - Perda de Peso / Emagrecimento\n*2️⃣* - Ganho de Massa Muscular e Definição\n*3️⃣* - Saúde, Condicionamento e Alívio do Estresse\n*4️⃣* - Reabilitação ou Fortalecimento',
        options: [
          { id: 'ob-1', key: '1', label: 'Emagrecimento', nextStepId: 'step-fit-horario', action: 'qualify_lead' },
          { id: 'ob-2', key: '2', label: 'Hipertrofia', nextStepId: 'step-fit-horario', action: 'qualify_lead' },
          { id: 'ob-3', key: '3', label: 'Saúde Geral', nextStepId: 'step-fit-horario', action: 'qualify_lead' },
          { id: 'ob-4', key: '4', label: 'Reabilitação', nextStepId: 'step-fit-horario', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-fit-horario',
        title: 'Horário Preferido',
        type: 'question_choice',
        message: 'Qual período você prefere treinar?\n\n*1️⃣* - Manhã (06h às 11h)\n*2️⃣* - Tarde (12h às 17h)\n*3️⃣* - Noite (18h às 22h)',
        options: [
          { id: 'h-1', key: '1', label: 'Manhã', nextStepId: 'step-fit-final', action: 'qualify_lead' },
          { id: 'h-2', key: '2', label: 'Tarde', nextStepId: 'step-fit-final', action: 'qualify_lead' },
          { id: 'h-3', key: '3', label: 'Noite', nextStepId: 'step-fit-final', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-fit-final',
        title: 'Passe Livre Liberado',
        type: 'closing',
        message: 'Parabéns pela decisão! Já separamos seu *Passe Livre com Avaliação Física Inicial*. Nosso coordenador entrará em contato em instantes para agendar sua primeira visita!',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-fit-humano',
        title: 'Recepção Academia',
        type: 'closing',
        message: 'Nossa recepção já foi notificada e vai te atender aqui agora mesmo!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 12. ENERGIA SOLAR & ENGENHARIA
  {
    id: 'flow-energia-solar',
    name: '☀️ Energia Solar & Engenharia Elétrica',
    segment: 'Energia Solar & Engenharia',
    companyName: 'SolarMais Energia Sustentável',
    description: 'Simulação de economia na conta de luz (até 95%), envio de fatura, dimensionamento do gerador fotovoltaico.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos sua atenção! Quando desejar zerar a conta de luz, conte conosco.',
    faqRules: [
      {
        id: 'faq-sol-1',
        keywords: ['garantia', 'placas', 'vida util'],
        reply: 'Nossas placas solares possuem 25 anos de garantia de eficiência com inversores de alta tecnologia e monitoramento via aplicativo.',
      }
    ],
    steps: [
      {
        id: 'step-sol-inicio',
        title: 'Simulação Solar',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Aqui é da *{{minha_empresa}}*! ☀️🔋\n\nVocê sabia que pode economizar até 95% na sua fatura de energia todos os meses? Onde seria a instalação?\n\n*1️⃣* - Casa / Residência\n*2️⃣* - Empresa / Comércio / Escritório\n*3️⃣* - Galpão / Indústria\n*4️⃣* - Propriedade Rural / Chácara\n*5️⃣* - Falar com Engenheiro`,
        options: [
          { id: 'so-1', key: '1', label: 'Residência', nextStepId: 'step-sol-valor' },
          { id: 'so-2', key: '2', label: 'Comércio', nextStepId: 'step-sol-valor' },
          { id: 'so-3', key: '3', label: 'Indústria', nextStepId: 'step-sol-valor' },
          { id: 'so-4', key: '4', label: 'Rural', nextStepId: 'step-sol-valor' },
          { id: 'so-5', key: '5', label: 'Engenheiro', nextStepId: 'step-sol-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-sol-valor',
        title: 'Média da Conta de Luz',
        type: 'question_choice',
        message: 'Qual é o valor médio da sua conta de luz mensal?\n\n*1️⃣* - R$ 300 a R$ 600 / mês\n*2️⃣* - R$ 600 a R$ 1.500 / mês\n*3️⃣* - Acima de R$ 1.500 / mês',
        options: [
          { id: 'vl-1', key: '1', label: '300 a 600', nextStepId: 'step-sol-coleta', action: 'qualify_lead' },
          { id: 'vl-2', key: '2', label: '600 a 1500', nextStepId: 'step-sol-coleta', action: 'qualify_lead' },
          { id: 'vl-3', key: '3', label: 'Mais de 1500', nextStepId: 'step-sol-coleta', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-sol-coleta',
        title: 'Foto da Conta ou Endereço',
        type: 'question_text',
        message: 'Excelente! Se tiver fácil, você pode enviar uma foto da conta de luz ou digitar sua *Cidade e Bairro* para calcularmos a irradiação solar ideal:',
        freeTextNextStepId: 'step-sol-final',
        saveToField: 'dados_conta_luz',
      },
      {
        id: 'step-sol-final',
        title: 'Estudo de Viabilidade',
        type: 'closing',
        message: 'Dados computados com sucesso! Nosso engenheiro já está gerando sua simulação 3D com a estimativa de placas, retorno financeiro e opções com parcelas que cabem na economia gerada. Aguarde só um instante! ☀️',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-sol-humano',
        title: 'Engenheiro de Plantão',
        type: 'closing',
        message: 'Nosso especialista em energia fotovoltaica já assumirá este chat para tirar todas as dúvidas técnicas!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 13. CURSOS, ESCOLAS & IDIOMAS
  {
    id: 'flow-escola-cursos',
    name: '🎓 Cursos, Idiomas & Treinamentos',
    segment: 'Educação & Treinamentos',
    companyName: 'Instituto Avançar Idiomas & Cursos',
    description: 'Matrículas, teste de nível de inglês, cursos profissionalizantes e consulta de bolsas de estudo.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o retorno! Quando desejar investir no seu futuro profissional, estaremos à disposição.',
    faqRules: [
      {
        id: 'faq-edu-1',
        keywords: ['certificado', 'reconhecido', 'mec', 'diploma'],
        reply: 'Todos os nossos cursos emitem certificado oficial reconhecido em todo o território nacional, com comprovação de carga horária para enriquecer seu currículo.',
      }
    ],
    steps: [
      {
        id: 'step-edu-inicio',
        title: 'Área de Estudo',
        type: 'question_choice',
        message: `{Olá|Oi}! Bem-vindo(a) ao *{{minha_empresa}}*! 🎓📚\n\nQual área você gostaria de alavancar para conquistar novas oportunidades?\n\n*1️⃣* - Idiomas (Inglês do Zero ao Avançado)\n*2️⃣* - Cursos Profissionalizantes & Tecnologia\n*3️⃣* - Pré-Vestibular / ENEM / Concursos\n*4️⃣* - Consultar Bolsas de Estudo com Desconto\n*5️⃣* - Falar com a Secretaria Pedagógica`,
        options: [
          { id: 'ed-1', key: '1', label: 'Idiomas', nextStepId: 'step-edu-publico' },
          { id: 'ed-2', key: '2', label: 'Profissionalizantes', nextStepId: 'step-edu-publico' },
          { id: 'ed-3', key: '3', label: 'Vestibular/Concursos', nextStepId: 'step-edu-publico' },
          { id: 'ed-4', key: '4', label: 'Bolsas', nextStepId: 'step-edu-publico' },
          { id: 'ed-5', key: '5', label: 'Secretaria', nextStepId: 'step-edu-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-edu-publico',
        title: 'Público Alvo',
        type: 'question_choice',
        message: 'O curso seria para você ou para outra pessoa (filho/cônjuge)?\n\n*1️⃣* - Para mim mesmo(a)\n*2️⃣* - Para meu filho(a) / adolescente / criança\n*3️⃣* - Para colaboradores da minha empresa',
        options: [
          { id: 'pb-1', key: '1', label: 'Para mim', nextStepId: 'step-edu-nome', action: 'qualify_lead' },
          { id: 'pb-2', key: '2', label: 'Para filho(a)', nextStepId: 'step-edu-nome', action: 'qualify_lead' },
          { id: 'pb-3', key: '3', label: 'Corporativo', nextStepId: 'step-edu-nome', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-edu-nome',
        title: 'Nome para Reserva',
        type: 'question_text',
        message: 'Ótimo! Por favor, digite seu *Nome Completo* para checarmos as bolsas e turmas disponíveis:',
        freeTextNextStepId: 'step-edu-final',
        saveToField: 'nome_aluno',
      },
      {
        id: 'step-edu-final',
        title: 'Condição Especial Liberada',
        type: 'closing',
        message: 'Reserva registrada com sucesso! Nosso consultor educacional já está assumindo a conversa para te apresentar as opções de turmas, metodologia e a bolsa especial. Até já! 🎓',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-edu-humano',
        title: 'Secretaria Educacional',
        type: 'closing',
        message: 'Um de nossos orientadores pedagógicos falará com você aqui em instantes!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 14. SEGURANÇA ELETRÔNICA, CFTV & ALARMES
  {
    id: 'flow-seguranca-eletronica',
    name: '🛡️ Segurança Eletrônica, CFTV & Alarmes',
    segment: 'Segurança & Monitoramento',
    companyName: 'VigiaSeg Segurança Eletrônica',
    description: 'Câmeras IP com visualização no celular, alarme com monitoramento 24h, portaria remota e cerca elétrica.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos o retorno! Salve nosso contato para manter seu patrimônio protegido e seguro.',
    faqRules: [
      {
        id: 'faq-seg-1',
        keywords: ['celular', 'aplicativo', 'ao vivo', 'grava'],
        reply: 'Sim! Nossos sistemas permitem ver as câmeras ao vivo pelo celular com gravação contínua em nuvem ou gravador DVR/NVR de alta definição.',
      }
    ],
    steps: [
      {
        id: 'step-seg-inicio',
        title: 'Solução de Segurança',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Aqui é da *{{minha_empresa}}*! 🛡️📹\n\nProtegemos o que mais importa com tecnologia de ponta. Qual proteção você procura hoje?\n\n*1️⃣* - Câmeras de Segurança (CFTV com acesso no celular)\n*2️⃣* - Alarme Monitorado 24h & Sensores de Intrusão\n*3️⃣* - Cerca Elétrica / Concertina\n*4️⃣* - Controle de Acesso / Interfonia / Portaria\n*5️⃣* - Falar com Especialista em Segurança`,
        options: [
          { id: 'sgo-1', key: '1', label: 'Câmeras', nextStepId: 'step-seg-local' },
          { id: 'sgo-2', key: '2', label: 'Alarmes', nextStepId: 'step-seg-local' },
          { id: 'sgo-3', key: '3', label: 'Cerca Elétrica', nextStepId: 'step-seg-local' },
          { id: 'sgo-4', key: '4', label: 'Controle Acesso', nextStepId: 'step-seg-local' },
          { id: 'sgo-5', key: '5', label: 'Especialista', nextStepId: 'step-seg-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-seg-local',
        title: 'Tipo de Imóvel',
        type: 'question_choice',
        message: 'Onde será a instalação ou manutenção do sistema?\n\n*1️⃣* - Casa ou Condomínio Residencial\n*2️⃣* - Comércio ou Loja de Rua\n*3️⃣* - Galpão ou Empresa de Médio/Grande Porte',
        options: [
          { id: 'lc-1', key: '1', label: 'Casa', nextStepId: 'step-seg-coleta', action: 'qualify_lead' },
          { id: 'lc-2', key: '2', label: 'Comércio', nextStepId: 'step-seg-coleta', action: 'qualify_lead' },
          { id: 'lc-3', key: '3', label: 'Empresa / Galpão', nextStepId: 'step-seg-coleta', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-seg-coleta',
        title: 'Bairro e Nome',
        type: 'question_text',
        message: 'Perfeito! Para agendarmos uma avaliação técnica presencial gratuita no local, qual é o seu *Nome e Bairro/Região*?',
        freeTextNextStepId: 'step-seg-final',
        saveToField: 'local_instalacao',
      },
      {
        id: 'step-seg-final',
        title: 'Visita Técnica Agendada',
        type: 'closing',
        message: 'Solicitação registrada! Nosso especialista em segurança entrará em contato para agendar o levantamento no local e fornecer o orçamento com instalação e suporte inclusos. 🛡️',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-seg-humano',
        title: 'Técnico de Plantão',
        type: 'closing',
        message: 'Nosso consultor técnico já vai te atender aqui para sanar dúvidas!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },

  // 15. LIMPEZA, DEDETIZAÇÃO & SERVIÇOS RESIDENCIAIS
  {
    id: 'flow-servicos-limpeza',
    name: '🧹 Limpeza, Dedetização & Serviços Prediais',
    segment: 'Serviços Residenciais & Prediais',
    companyName: 'LimpMais & Dedetização Express',
    description: 'Orçamento de limpeza pós-obra, diarista corporativa, dedetização de baratas, cupins e pragas urbanas.',
    isActive: false,
    isTemplate: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    rejectionMessage: 'Agradecemos sua atenção! Quando precisar de um ambiente higienizado e livre de pragas, conte conosco.',
    faqRules: [
      {
        id: 'faq-lmp-1',
        keywords: ['cheiro', 'animais', 'pet', 'perigo', 'seguro'],
        reply: 'Utilizamos produtos autorizados pela Anvisa, sem cheiro forte e totalmente seguros para sua família e animais de estimação!',
      }
    ],
    steps: [
      {
        id: 'step-lmp-inicio',
        title: 'Tipo de Serviço',
        type: 'question_choice',
        message: `{Olá|Oi|Tudo bem?} Seja bem-vindo(a) à *{{minha_empresa}}*! 🧹✨🐜\n\nAmbientes limpos, protegidos e impecáveis. Qual serviço você precisa?\n\n*1️⃣* - Dedetização contra Baratas, Formigas, Ratos ou Cupins\n*2️⃣* - Limpeza Pós-Obra ou Pré-Mudança\n*3️⃣* - Higienização de Estofados, Sofás e Colchões\n*4️⃣* - Limpeza Comercial / Escritórios Recorrente\n*5️⃣* - Falar com o Orçamentista`,
        options: [
          { id: 'lo-1', key: '1', label: 'Dedetização', nextStepId: 'step-lmp-tamanho' },
          { id: 'lo-2', key: '2', label: 'Pós-Obra', nextStepId: 'step-lmp-tamanho' },
          { id: 'lo-3', key: '3', label: 'Sofás/Estofados', nextStepId: 'step-lmp-tamanho' },
          { id: 'lo-4', key: '4', label: 'Comercial Recorrente', nextStepId: 'step-lmp-tamanho' },
          { id: 'lo-5', key: '5', label: 'Orçamentista', nextStepId: 'step-lmp-humano', action: 'transfer_human' },
        ],
      },
      {
        id: 'step-lmp-tamanho',
        title: 'Tamanho do Imóvel',
        type: 'question_choice',
        message: 'Para estimarmos a quantidade de equipe e materiais, qual é o porte aproximado do imóvel?\n\n*1️⃣* - Apartamento pequeno (até 70m²)\n*2️⃣* - Apartamento grande ou Casa (de 70m² a 150m²)\n*3️⃣* - Casa ampla, Sobrado ou Empresa (acima de 150m²)',
        options: [
          { id: 'tm-1', key: '1', label: 'Até 70m²', nextStepId: 'step-lmp-coleta', action: 'qualify_lead' },
          { id: 'tm-2', key: '2', label: '70m² a 150m²', nextStepId: 'step-lmp-coleta', action: 'qualify_lead' },
          { id: 'tm-3', key: '3', label: 'Mais de 150m²', nextStepId: 'step-lmp-coleta', action: 'qualify_lead' },
        ],
      },
      {
        id: 'step-lmp-coleta',
        title: 'Bairro e Nome',
        type: 'question_text',
        message: 'Perfeito! Qual é o seu *Nome e Bairro* para localizarmos nossa equipe mais próxima?',
        freeTextNextStepId: 'step-lmp-final',
        saveToField: 'dados_servico_limpeza',
      },
      {
        id: 'step-lmp-final',
        title: 'Orçamento com Certificado',
        type: 'closing',
        message: 'Informações computadas! Nosso orçamentista entrará em contato aqui em instantes para passar os valores exatos e disponibilidade de agenda com certificado de garantia. Aguarde só um momento! 🧹✨',
        isEnd: true,
        action: 'transfer_human',
      },
      {
        id: 'step-lmp-humano',
        title: 'Atendente de Serviços',
        type: 'closing',
        message: 'Nosso plantão de atendimento já vai falar com você aqui!',
        isEnd: true,
        action: 'transfer_human',
      },
    ],
  },
];

